### ISSUE TITLE
How can I rename some services

### ISSUE THREAD

**Issue by PrasBiswas2016** [bipingupta/Microservices-Demo#1]
I want to rename
Noun - Catalog or Product service
Adjective - Review service
Article - Payment service
Subject -  Offer service
Sentence - Order service

How can I do this?

(Not an issue but a customization)

**Comment by bipingupta** [comment]
In  bootstrap.yml file contains configuration. So change them as per below :

spring:
  profiles: subject
  application:
    name: Offer service
 ---
spring:
  profiles: article
  application:
    name: Payment service
---
spring:
  profiles: adjective
  application:
    name: Review service
---
spring:
  profiles: noun
  application:
    name: Catalog service
